version: '3.1'

services:
  db:
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    image: mariadb:10.3
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: db_final
    ports:
      - 3306:3306
    networks:
      db-final-network:
        ipv4_address: 10.5.0.2

  apache:
    container_name: apache
    image: mobingi/ubuntu-apache2-php7:7.2
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./backend:/var/www/html
      - ./.env:/var/www/html/env
    networks:
      db-final-network:
        ipv4_address: 10.5.0.3
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_HOSTS: db
    depends_on:
      - db
    volumes:
      - ./frontend/RentHub:/app
    networks:
      db-final-network:
        ipv4_address: 10.5.0.4
  web:
    build:
      context: .
    command: npm run serve
    restart: always
    ports:
      - "8005:8080"
    environment:
      - NODE_ENV=development
      - DEBUG=nodejs-docker-express:*
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
    networks:
      db-final-network:
        ipv4_address: 10.5.0.5

networks:
  db-final-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
